'use strict'
const parser = require('parse-address')
const { wordsToNumbers } = require('words-to-numbers');
const ordinal = require('ordinal')

function abbrevStreet (input) {
  let res = Street_Type[input]
  return res || null
}

function checkNonsense (input) {
  let props = ['number', 'street', 'type']
  return props.map(function (prop) {
    if (input[prop] === undefined || input[prop] === null) {
      return true
    }
    return false
  }).includes(true)
}

let Street_Type = {
    ALLEE       : "ALY",
    ALLEY       : "ALY",
    ALLY        : "ALY",
    ANEX        : "ANX",
    ANNEX       : "ANX",
    ANNX        : "ANX",
    ARCADE      : "ARC",
    AV          : "AVE",
    AVEN        : "AVE",
    AVENU       : "AVE",
    AVENUE      : "AVE",
    AVN         : "AVE",
    AVNUE       : "AVE",
    BAYOO       : "BYU",
    BAYOU       : "BYU",
    BEACH       : "BCH",
    BEND        : "BND",
    BLUF        : "BLF",
    BLUFF       : "BLF",
    BLUFFS      : "BLFS",
    BOT         : "BTM",
    BOTTM       : "BTM",
    BOTTOM      : "BTM",
    BOUL        : "BLVD",
    BOULEVARD   : "BLVD",
    BOULV       : "BLVD",
    BRANCH      : "BR",
    BRDGE       : "BRG",
    BRIDGE      : "BRG",
    BRNCH       : "BR",
    BROOK       : "BRK",
    BROOKS      : "BRKS",
    BURG        : "BG",
    BURGS       : "BGS",
    BYPA        : "BYP",
    BYPAS       : "BYP",
    BYPASS      : "BYP",
    BYPS        : "BYP",
    CAMP        : "CP",
    CANYN       : "CYN",
    CANYON      : "CYN",
    CAPE        : "CPE",
    CAUSEWAY    : "CSWY",
    CAUSWAY     : "CSWY",
    CEN         : "CTR",
    CENT        : "CTR",
    CENTER      : "CTR",
    CENTERS     : "CTRS",
    CENTR       : "CTR",
    CENTRE      : "CTR",
    CIRC        : "CIR",
    CIRCL       : "CIR",
    CIRCLE      : "CIR",
    CIRCLES     : "CIRS",
    CK          : "CRK",
    CLIFF       : "CLF",
    CLIFFS      : "CLFS",
    CLUB        : "CLB",
    CMP         : "CP",
    CNTER       : "CTR",
    CNTR        : "CTR",
    CNYN        : "CYN",
    COMMON      : "CMN",
    CORNER      : "COR",
    CORNERS     : "CORS",
    COURSE      : "CRSE",
    COURT       : "CT",
    COURTS      : "CTS",
    COVE        : "CV",
    COVES       : "CVS",
    CR          : "CRK",
    CRCL        : "CIR",
    CRCLE       : "CIR",
    CRECENT     : "CRES",
    CREEK       : "CRK",
    CRESCENT    : "CRES",
    CRESENT     : "CRES",
    CREST       : "CRST",
    CROSSING    : "XING",
    CROSSROAD   : "XRD",
    CRSCNT      : "CRES",
    CRSENT      : "CRES",
    CRSNT       : "CRES",
    CRSSING     : "XING",
    CRSSNG      : "XING",
    CRT         : "CT",
    CURVE       : "CURV",
    DALE        : "DL",
    DAM         : "DM",
    DIV         : "DV",
    DIVIDE      : "DV",
    DRIV        : "DR",
    DRIVE       : "DR",
    DRIVES      : "DRS",
    DRV         : "DR",
    DVD         : "DV",
    ESTATE      : "EST",
    ESTATES     : "ESTS",
    EXP         : "EXPY",
    EXPR        : "EXPY",
    EXPRESS     : "EXPY",
    EXPRESSWAY  : "EXPY",
    EXPW        : "EXPY",
    EXTENSION   : "EXT",
    EXTENSIONS  : "EXTS",
    EXTN        : "EXT",
    EXTNSN      : "EXT",
    FALLS       : "FLS",
    FERRY       : "FRY",
    FIELD       : "FLD",
    FIELDS      : "FLDS",
    FLAT        : "FLT",
    FLATS       : "FLTS",
    FORD        : "FRD",
    FORDS       : "FRDS",
    FOREST      : "FRST",
    FORESTS     : "FRST",
    FORG        : "FRG",
    FORGE       : "FRG",
    FORGES      : "FRGS",
    FORK        : "FRK",
    FORKS       : "FRKS",
    FORT        : "FT",
    FREEWAY     : "FWY",
    FREEWY      : "FWY",
    FRRY        : "FRY",
    FRT         : "FT",
    FRWAY       : "FWY",
    FRWY        : "FWY",
    GARDEN      : "GDN",
    GARDENS     : "GDNS",
    GARDN       : "GDN",
    GATEWAY     : "GTWY",
    GATEWY      : "GTWY",
    GATWAY      : "GTWY",
    GLEN        : "GLN",
    GLENS       : "GLNS",
    GRDEN       : "GDN",
    GRDN        : "GDN",
    GRDNS       : "GDNS",
    GREEN       : "GRN",
    GREENS      : "GRNS",
    GROV        : "GRV",
    GROVE       : "GRV",
    GROVES      : "GRVS",
    GTWAY       : "GTWY",
    HARB        : "HBR",
    HARBOR      : "HBR",
    HARBORS     : "HBRS",
    HARBR       : "HBR",
    HAVEN       : "HVN",
    HAVN        : "HVN",
    HEIGHT      : "HTS",
    HEIGHTS     : "HTS",
    HGTS        : "HTS",
    HIGHWAY     : "HWY",
    HIGHWY      : "HWY",
    HILL        : "HL",
    HILLS       : "HLS",
    HIWAY       : "HWY",
    HIWY        : "HWY",
    HLLW        : "HOLW",
    HOLLOW      : "HOLW",
    HOLLOWS     : "HOLW",
    HOLWS       : "HOLW",
    HRBOR       : "HBR",
    HT          : "HTS",
    HWAY        : "HWY",
    INLET       : "INLT",
    ISLAND      : "IS",
    ISLANDS     : "ISS",
    ISLES       : "ISLE",
    ISLND       : "IS",
    ISLNDS      : "ISS",
    JCTION      : "JCT",
    JCTN        : "JCT",
    JCTNS       : "JCTS",
    JUNCTION    : "JCT",
    JUNCTIONS   : "JCTS",
    JUNCTN      : "JCT",
    JUNCTON     : "JCT",
    KEY         : "KY",
    KEYS        : "KYS",
    KNOL        : "KNL",
    KNOLL       : "KNL",
    KNOLLS      : "KNLS",
    LA          : "LN",
    LAKE        : "LK",
    LAKES       : "LKS",
    LANDING     : "LNDG",
    LANE        : "LN",
    LANES       : "LN",
    LDGE        : "LDG",
    LIGHT       : "LGT",
    LIGHTS      : "LGTS",
    LNDNG       : "LNDG",
    LOAF        : "LF",
    LOCK        : "LCK",
    LOCKS       : "LCKS",
    LODG        : "LDG",
    LODGE       : "LDG",
    LOOPS       : "LOOP",
    MANOR       : "MNR",
    MANORS      : "MNRS",
    MEADOW      : "MDW",
    MEADOWS     : "MDWS",
    MEDOWS      : "MDWS",
    MILL        : "ML",
    MILLS       : "MLS",
    MISSION     : "MSN",
    MISSN       : "MSN",
    MNT         : "MT",
    MNTAIN      : "MTN",
    MNTN        : "MTN",
    MNTNS       : "MTNS",
    MOTORWAY    : "MTWY",
    MOUNT       : "MT",
    MOUNTAIN    : "MTN",
    MOUNTAINS   : "MTNS",
    MOUNTIN     : "MTN",
    MSSN        : "MSN",
    MTIN        : "MTN",
    NECK        : "NCK",
    ORCHARD     : "ORCH",
    ORCHRD      : "ORCH",
    OVERPASS    : "OPAS",
    OVL         : "OVAL",
    PARKS       : "PARK",
    PARKWAY     : "PKWY",
    PARKWAYS    : "PKWY",
    PARKWY      : "PKWY",
    PASSAGE     : "PSGE",
    PATHS       : "PATH",
    PIKES       : "PIKE",
    PINE        : "PNE",
    PINES       : "PNES",
    PK          : "PARK",
    PKWAY       : "PKWY",
    PKWYS       : "PKWY",
    PKY         : "PKWY",
    PLACE       : "PL",
    PLAIN       : "PLN",
    PLAINES     : "PLNS",
    PLAINS      : "PLNS",
    PLAZA       : "PLZ",
    PLZA        : "PLZ",
    POINT       : "PT",
    POINTS      : "PTS",
    PORT        : "PRT",
    PORTS       : "PRTS",
    PRAIRIE     : "PR",
    PRARIE      : "PR",
    PRK         : "PARK",
    PRR         : "PR",
    RAD         : "RADL",
    RADIAL      : "RADL",
    RADIEL      : "RADL",
    RANCH       : "RNCH",
    RANCHES     : "RNCH",
    RAPID       : "RPD",
    RAPIDS      : "RPDS",
    RDGE        : "RDG",
    REST        : "RST",
    RIDGE       : "RDG",
    RIDGES      : "RDGS",
    RIVER       : "RIV",
    RIVR        : "RIV",
    RNCHS       : "RNCH",
    ROAD        : "RD",
    ROADS       : "RDS",
    ROUTE       : "RTE",
    RVR         : "RIV",
    ROW         : "ROW",
    SHOAL       : "SHL",
    SHOALS      : "SHLS",
    SHOAR       : "SHR",
    SHOARS      : "SHRS",
    SHORE       : "SHR",
    SHORES      : "SHRS",
    SKYWAY      : "SKWY",
    SPNG        : "SPG",
    SPNGS       : "SPGS",
    SPRING      : "SPG",
    SPRINGS     : "SPGS",
    SPRNG       : "SPG",
    SPRNGS      : "SPGS",
    SPURS       : "SPUR",
    SQR         : "SQ",
    SQRE        : "SQ",
    SQRS        : "SQS",
    SQU         : "SQ",
    SQUARE      : "SQ",
    SQUARES     : "SQS",
    STATION     : "STA",
    STATN       : "STA",
    STN         : "STA",
    STR         : "ST",
    STRAV       : "STRA",
    STRAVE      : "STRA",
    STRAVEN     : "STRA",
    STRAVENUE   : "STRA",
    STRAVN      : "STRA",
    STREAM      : "STRM",
    STREET      : "ST",
    STREETS     : "STS",
    STREME      : "STRM",
    STRT        : "ST",
    STRVN       : "STRA",
    STRVNUE     : "STRA",
    SUMIT       : "SMT",
    SUMITT      : "SMT",
    SUMMIT      : "SMT",
    TERR        : "TER",
    TERRACE     : "TER",
    THROUGHWAY  : "TRWY",
    TPK         : "TPKE",
    TR          : "TRL",
    TRACE       : "TRCE",
    TRACES      : "TRCE",
    TRACK       : "TRAK",
    TRACKS      : "TRAK",
    TRAFFICWAY  : "TRFY",
    TRAIL       : "TRL",
    TRAILS      : "TRL",
    TRK         : "TRAK",
    TRKS        : "TRAK",
    TRLS        : "TRL",
    TRNPK       : "TPKE",
    TRPK        : "TPKE",
    TUNEL       : "TUNL",
    TUNLS       : "TUNL",
    TUNNEL      : "TUNL",
    TUNNELS     : "TUNL",
    TUNNL       : "TUNL",
    TURNPIKE    : "TPKE",
    TURNPK      : "TPKE",
    UNDERPASS   : "UPAS",
    UNION       : "UN",
    UNIONS      : "UNS",
    VALLEY      : "VLY",
    VALLEYS     : "VLYS",
    VALLY       : "VLY",
    VDCT        : "VIA",
    VIADCT      : "VIA",
    VIADUCT     : "VIA",
    VIEW        : "VW",
    VIEWS       : "VWS",
    VILL        : "VLG",
    VILLAG      : "VLG",
    VILLAGE     : "VLG",
    VILLAGES    : "VLGS",
    VILLE       : "VL",
    VILLG       : "VLG",
    VILLIAGE    : "VLG",
    VIST        : "VIS",
    VISTA       : "VIS",
    VLLY        : "VLY",
    VST         : "VIS",
    VSTA        : "VIS",
    WALKS       : "WALK",
    WELL        : "WL",
    WELLS       : "WLS",
    WY          : "WAY",
    ALY : "ALY",
    ANX : "ANX",
    ARC : "ARC",
    AVE : "AVE",
    BYU : "BYU",
    BCH : "BCH",
    BND : "BND",
    BLF : "BLF",
    BLFS : "BLFS",
    BTM : "BTM",
    BLVD : "BLVD",
    BR : "BR",
    BRG : "BRG",
    BRK : "BRK",
    BRKS : "BRKS",
    BG : "BG",
    BGS : "BGS",
    BYP : "BYP",
    CP : "CP",
    CYN : "CYN",
    CPE : "CPE",
    CSWY : "CSWY",
    CTR : "CTR",
    CTRS : "CTRS",
    CIR : "CIR",
    CIRS : "CIRS",
    CRK : "CRK",
    CLF : "CLF",
    CLFS : "CLFS",
    CLB : "CLB",
    CMN : "CMN",
    COR : "COR",
    CORS : "CORS",
    CRSE : "CRSE",
    CT : "CT",
    CTS : "CTS",
    CV : "CV",
    CVS : "CVS",
    CRES : "CRES",
    CRST : "CRST",
    XING : "XING",
    XRD : "XRD",
    CURV : "CURV",
    DL : "DL",
    DM : "DM",
    DV : "DV",
    DR : "DR",
    DRS : "DRS",
    EST : "EST",
    ESTS : "ESTS",
    EXPY : "EXPY",
    EXT : "EXT",
    EXTS : "EXTS",
    FLS : "FLS",
    FRY : "FRY",
    FLD : "FLD",
    FLDS : "FLDS",
    FLT : "FLT",
    FLTS : "FLTS",
    FRD : "FRD",
    FRDS : "FRDS",
    FRST : "FRST",
    FRG : "FRG",
    FRGS : "FRGS",
    FRK : "FRK",
    FRKS : "FRKS",
    FT : "FT",
    FWY : "FWY",
    GDN : "GDN",
    GDNS : "GDNS",
    GTWY : "GTWY",
    GLN : "GLN",
    GLNS : "GLNS",
    GRN : "GRN",
    GRNS : "GRNS",
    GRV : "GRV",
    GRVS : "GRVS",
    HBR : "HBR",
    HBRS : "HBRS",
    HVN : "HVN",
    HTS : "HTS",
    HWY : "HWY",
    HL : "HL",
    HLS : "HLS",
    HOLW : "HOLW",
    INLT : "INLT",
    IS : "IS",
    ISS : "ISS",
    ISLE : "ISLE",
    JCT : "JCT",
    JCTS : "JCTS",
    KY : "KY",
    KYS : "KYS",
    KNL : "KNL",
    KNLS : "KNLS",
    LN : "LN",
    LK : "LK",
    LKS : "LKS",
    LNDG : "LNDG",
    LDG : "LDG",
    LGT : "LGT",
    LGTS : "LGTS",
    LF : "LF",
    LCK : "LCK",
    LCKS : "LCKS",
    LOOP : "LOOP",
    MNR : "MNR",
    MNRS : "MNRS",
    MDW : "MDW",
    MDWS : "MDWS",
    ML : "ML",
    MLS : "MLS",
    MSN : "MSN",
    MT : "MT",
    MTN : "MTN",
    MTNS : "MTNS",
    MTWY : "MTWY",
    NCK : "NCK",
    ORCH : "ORCH",
    OPAS : "OPAS",
    OVAL : "OVAL",
    PARK : "PARK",
    PKWY : "PKWY",
    PSGE : "PSGE",
    PATH : "PATH",
    PIKE : "PIKE",
    PNE : "PNE",
    PNES : "PNES",
    PL : "PL",
    PLN : "PLN",
    PLNS : "PLNS",
    PLZ : "PLZ",
    PT : "PT",
    PTS : "PTS",
    PRT : "PRT",
    PRTS : "PRTS",
    PR : "PR",
    RADL : "RADL",
    RNCH : "RNCH",
    RPD : "RPD",
    RPDS : "RPDS",
    RDG : "RDG",
    RST : "RST",
    RDGS : "RDGS",
    RIV : "RIV",
    RD : "RD",
    RDS : "RDS",
    RTE : "RTE",
    ROW : "ROW",
    SHL : "SHL",
    SHLS : "SHLS",
    SHR : "SHR",
    SHRS : "SHRS",
    SKWY : "SKWY",
    SPG : "SPG",
    SPGS : "SPGS",
    SPUR : "SPUR",
    SQ : "SQ",
    SQS : "SQS",
    STA : "STA",
    ST : "ST",
    STRA : "STRA",
    STRM : "STRM",
    STS : "STS",
    SMT : "SMT",
    TER : "TER",
    TRWY : "TRWY",
    TPKE : "TPKE",
    TRL : "TRL",
    TRCE : "TRCE",
    TRAK : "TRAK",
    TRFY : "TRFY",
    TUNL : "TUNL",
    UPAS : "UPAS",
    UN : "UN",
    UNS : "UNS",
    VLY : "VLY",
    VLYS : "VLYS",
    VIA : "VIA",
    VW : "VW",
    VWS : "VWS",
    VLG : "VLG",
    VLGS : "VLGS",
    VL : "VL",
    VIS : "VIS",
    WALK : "WALK",
    WL : "WL",
    WLS : "WLS",
    WAY : "WAY",
  }

let under10 = [
  '1ST',
  '2ND',
  '3RD',
  '4TH',
  '5TH',
  '6TH',
  '7TH',
  '8TH',
  '9TH',
  '1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
]

/** @function standardize
 * @param {object} address
 * @param {string} address.address - the address
 * @returns {object} standardized address object
 */
function standardize (address) {
  let parsed = prep(address.address)
  return Object.assign({}, address, parsed, {address: normalString(address.address)})
}

/** @function normalString
 * @param {string} address - containing number street type
 * @returns {string} normalized address string that looks like the ones from DataSF
 */
function normalString (address) {
  let parsed = prep(address)
  if (parsed === null) { return null }
  return `${parsed.number} ${parsed.street} ${parsed.type}`.toUpperCase()
}

/** @function prep
 * @param {string} address - containing number street type
 * @returns {string}
 *
 */
function prep (address) {
  let prepped = address.replace(/![a-zA-Z0-9]/g, '').toUpperCase()
  let parsed = parser.parseLocation(prepped)
  if (checkNonsense(parsed)) { return null }
  let ordinalStreet = wordsToNumbers(parsed.street)
  if (typeof ordinalStreet === 'number') {
    parsed.street = ordinal(ordinalStreet)
  }
  if (under10.includes(parsed.street)) {
    parsed.street = `0${parsed.street}`
  }
  parsed.type = abbrevStreet(parsed.type).toUpperCase()
  return parsed
}

/** @function nextDoor
 * @param {object} address - a normalized address object
 * @param {string} upDown - find next street number going up or down
 * @returns {object} - adds or subtracts 2 to the street number
 */
function nextDoor (address, upDown = 'up') {
  let res = Object.assign({}, address)
  res.number = (upDown === 'down') ? +res.number - 2 : +res.number + 2
  res.number = res.number.toString()
  res.address = `${res.number} ${res.street} ${res.type}`
  return res
}

module.exports = { standardize, normalString, nextDoor }
